### PR TITLE
feat: add ODE test endpoint

### PR DESCRIPTION
**Pull request by mwdchang**
### Summary
Add an ODE test end-point to get a sense of what simulation should be like. This is a temporary solution for development purposes and is meant to be replaced by TA3 endpoints once they come online.

There are two ways to run this, you can either use docker
```
docker build . -t model-transform
docker run -p 8888:8888 model-transform
```
Or run with Julia
```
julia src/service.jl
```

### Testing
This snippet create a predator/prey petri-net and runs the simulate endpoint. Replace ":modelId" with the modelId you get back from the PUT request.

```
curl -XPUT -H "Content-type: application/json" localhost:8888/api/models
curl -XPOST -H "Content-type: application/json" localhost:8888/api/models/:modelId -d@rabbit-wolf.json
curl -XPOST -H "Content-type: application/json" localhost:8888/api/models/:modelId/simulate -d@rabbit-wolf-params.json
```

File rabbit-wolf.json
```
{
  "nodes": [
    { "name": "rabbits", "type": "S" },
    { "name": "wolves", "type": "S" },
    { "name": "birth", "type": "T" },
    { "name": "predation", "type": "T" },
    { "name": "death", "type": "T" }
  ],
  "edges": [
    { "source": "wolves", "target": "death" },

    { "source": "predation", "target": "wolves" },
    { "source": "predation", "target": "wolves" },
    { "source": "wolves", "target": "predation" },
    { "source": "rabbits", "target": "predation" },

    { "source": "rabbits", "target": "birth" },
    { "source": "birth", "target": "rabbits" },
    { "source": "birth", "target": "rabbits" }
  ]
}
```

File rabbit-wolf-params.json
```
{
  "variables": {
    "rabbits": 100.0,
    "wolves": 10.0
  },
  "parameters": {
    "birth": 0.3,
    "predation": 0.015,
    "death": 0.7
  }
}
```

You should get something that looks like
```
{"id":"xyz"}"done"{"variables":["rabbits","wolves"],"u":[[100.0,10.0],[101.58846,10.935402],[104.85833,13.80621],[107.032234,19.70691],[104.05303,29.303474],[90.90408,44.506508],[65.361084,60.940826],[42.283382,64.97572],[26.269268,55.69383],[17.609612,38.112366],[15.092785,24.994436],[15.2682085,14.586457],[18.304379,7.999409],[24.973219,4.5517783],[37.952927,3.0416615],[57.262566,3.0624428],[101.04658,10.657256],[101.92049,32.432663],[59.51018,63.005737],[25.694828,54.63843],[17.02533,35.488983],[14.954796,18.767418],[17.129238,9.674611],[23.773216,4.957967],[37.71703,3.0887818],[58.125587,3.130243],[102.396164,11.883904],[100.18981,34.21173],[58.48643,63.002995],[26.75397,55.691025],[17.23799,35.985046],[15.007083,19.710989],[16.911474,10.195124],[23.11191,5.232645],[36.344845,3.182748],[55.78292,3.0797799],[99.11102,9.927663],[102.19096,31.104765],[59.72363,62.424484],[26.762957,55.476105],[17.631517,37.101013],[15.079102,20.114002],[16.779154,10.614958],[22.80382,5.4032907],[35.46895,3.2625234],[54.444164,3.0702922],[94.25642,7.999561],[103.60765,28.360096],[59.920135,62.13978],[27.157953,55.712353],[17.243618,35.384705],[15.149806,18.967674],[17.433462,9.586014],[24.292208,4.93595],[38.805344,3.1223922],[59.94783,3.2836697],[103.424736,13.622536],[97.81108,36.136066],[57.584545,62.640564],[27.435377,55.837894],[17.565348,36.32594],[15.198013,20.350864],[16.903917,10.64232],[22.847553,5.477834],[35.564934,3.3047574],[54.431507,3.1147966],[94.42996,8.227985],[103.03838,28.579817],[59.951622,61.774467],[26.909489,55.03802],[17.343733,35.18653],[15.281812,18.692184],[15.9089985,13.639963]],"t":[0.0,0.11011316046003701,0.3844461364314774,0.78258226229923,1.2275968647535116,1.7668010298211334,2.4248456530492337,3.082505884955552,3.853667598460366,4.846310185227981,5.765702729371114,6.898026000909611,8.228158436876845,9.711784256183412,11.41789447884953,13.024845681224626,15.601776522479952,16.871803569670742,18.098026297945776,19.43011147432789,20.530660556866895,21.894354269514256,23.3235583901606,24.999208086291738,26.90137793158186,28.59532276602242,31.23337829952513,32.445592421345,33.63113351916917,34.8670452732505,36.004280548190664,37.299304647120046,38.71735496623954,40.36310263322891,42.24925656249948,43.929963739925505,46.50272973545277,47.82481954782614,49.09357280056848,50.36749905878427,51.42746736835754,52.75286094970533,54.12689845235068,55.77946812644956,57.634261641276524,59.31891854680193,61.692460702368955,63.19790091718036,64.57070569390422,65.82846144869652,67.01661377518224,68.36057581436943,69.8432971099958,71.53249556535735,73.46324087897942,75.17500267360398,77.83084447174886,78.96705354341063,80.10228593667924,81.2841165275787,82.42490798524581,83.68241930596817,85.08101944556635,86.71192140640397,88.576375807858,90.25374060619015,92.65112556365588,94.1385357955369,95.50050966251693,96.78762743592281,97.95741019505611,99.3253990847365,100.0]}%
```

### CODE REVIEW

**Review by YohannParis — APPROVED** [review]
Works on my end

**Comment by bencodrington** [comment]
1. I ran the service successfully
2. I created and pasted in the two files
3. When trying to POST the model file I got an error
```
{
  "error": "500 Internal Error - MethodError: no method matching keys(::Catlab.ColumnImplementations.DenseAttr{Symbol})
  Closest candidates are:
    keys(!Matched::Union{Tables.AbstractColumns, Tables.AbstractRow}) at ~/.julia/packages/Tables/T7rHm/src/Tables.jl:189
    keys(!Matched::IOContext) at show.jl:345
    keys(!Matched::ChainRulesCore.Tangent) at ~/.julia/packages/ChainRulesCore/C73ay/src/tangent_types/tangent.jl:133
    ...
  Stacktrace:
    [1] pairs(collection::Catlab.ColumnImplementations.DenseAttr{Symbol})
      @ Base ./abstractdict.jl:172
    [2] findfirst(testf::Main.demo.var\"#6#13\"{Symbol}, A::Catlab.ColumnImplementations.DenseAttr{Symbol})
      @ Base ./array.jl:2067
    [3] (::Main.demo.var\"#5#12\")()
      @ Main.demo /model-transform/service.jl:91
    [4] run_route(r::Genie.Router.Route)
      @ Genie.Router ~/.julia/packages/Genie/bTQCj/src/Router.jl:535
    [5] route_request(req::HTTP.Messages.Request, res::HTTP.Messages.Response)
      @ Genie.Router ~/.julia/packages/Genie/bTQCj/src/Router.jl:173
    [6] handle_request(req::HTTP.Messages.Request, res::HTTP.Messages.Response)
      @ Genie.Server ~/.julia/packages/Genie/bTQCj/src/Server.jl:270
    [7] (::Genie.Server.var\"#27#28\"{HTTP.Messages.Request, HTTP.Messages.Response})()
      @ Genie.Server /usr/local/julia/share/julia/stdlib/v1.8/Distributed/src/macros.jl:123
    [8] #invokelatest#2
      @ ./essentials.jl:729 [inlined]
    [9] invokelatest
      @ ./essentials.jl:726 [inlined]
   [10] #153
      @ /usr/local/julia/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:425 [inlined]
   [11] run_work_thunk(thunk::Distributed.var\"#153#154\"{Genie.Server.var\"#27#28\"{HTTP.Messages.Request, HTTP.Messages.Response}, Tuple{}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}, print_error::Bool)
      @ Distributed /usr/local/julia/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:70
   [12] #remotecall_fetch#158
      @ /usr/local/julia/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:450 [inlined]
   [13] remotecall_fetch
      @ /usr/local/julia/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:449 [inlined]
   [14] #remotecall_fetch#162
      @ /usr/local/julia/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:492 [inlined]
   [15] remotecall_fetch
      @ /usr/local/julia/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:492 [inlined]
   [16] setup_http_listener(req::HTTP.Messages.Request, res::HTTP.Messages.Response)
      @ Genie.Server ~/.julia/packages/Genie/bTQCj/src/Server.jl:297
   [17] setup_http_listener
      @ ~/.julia/packages/Genie/bTQCj/src/Server.jl:296 [inlined]
   [18] (::HTTP.Handlers.var\"#1#2\"{typeof(Genie.Server.setup_http_listener)})(stream::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Connection})
      @ HTTP.Handlers ~/.julia/packages/HTTP/fthyG/src/Handlers.jl:58
   [19] setup_http_streamer(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Connection})
      @ Genie.Server ~/.julia/packages/Genie/bTQCj/src/Server.jl:286
   [20] (::Genie.Server.var\"#6#12\"{Int64})(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Connection})
      @ Genie.Server ~/.julia/packages/Genie/bTQCj/src/Server.jl:118
   [21] #invokelatest#2
      @ ./essentials.jl:729 [inlined]
   [22] invokelatest
      @ ./essentials.jl:726 [inlined]
   [23] handle_connection(f::Function, c::HTTP.ConnectionPool.Connection, listener::HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, readtimeout::Int64, access_log::Nothing)
      @ HTTP.Servers ~/.julia/packages/HTTP/fthyG/src/Servers.jl:442
   [24] (::HTTP.Servers.var\"#16#17\"{Genie.Server.var\"#6#12\"{Int64}, HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, Set{HTTP.ConnectionPool.Connection}, Int64, Nothing, Base.Semaphore, HTTP.ConnectionPool.Connection})()
      @ HTTP.Servers ./task.jl:484
```

**Comment by mwdchang** [comment]
@bencodrington are you running this inside Docker? or are you running this in the CLI with julia direclty?
It might be that the dependency is messed up as there are some recent updates to the packages?

```
(@v1.7) pkg> status
      Status `~/.julia/environments/v1.7/Project.toml`
  [4f99eebe] AlgebraicPetri v0.7.3
  [134e5e36] Catlab v0.14.5
  [c43c736e] Genie v5.2.2
  [7073ff75] IJulia v1.23.3
  [682c06a0] JSON v0.21.3
  [1dea7af3] OrdinaryDiffEq v6.28.1
```

**Review by YohannParis — APPROVED** [review]
It finally worked for me
```bash
yparis@yparis-uncharted ~ % curl -XPOST -H "Content-type: application/json" localhost:8888/api/models/86a4ec22-68ff-4b36-92df-29c973decb74/simulate -d@Desktop/rabbit-wolf-params.json
{"variables":["rabbits","wolves"],"u":[[100.0,10.0],[101.58846,10.935402],[104.85832,13.806213],[107.03602,19.969694],[103.870125,29.617338],[90.240036,45.088013],[64.45807,61.318085],[41.573612,64.85974],[25.866938,55.196804],[17.488571,37.686234],[15.058224,24.618223],[15.314246,14.340862],[18.454151,7.8484206],[25.271734,4.4772544],[38.377327,3.024833],[58.03972,3.0894227],[100.03556,10.055396],[102.5868,31.514282],[60.43265,62.728813],[27.221281,56.585434],[17.777716,38.413944],[14.911501,21.028202],[16.302528,11.201281],[21.8418,5.6595516],[33.33136,3.3383944],[51.255596,2.9375424],[85.50757,5.651312],[105.605484,25.623392],[72.94132,56.991364],[36.435654,63.192406],[21.120419,47.25989],[15.320264,26.634024],[15.281201,14.795704],[19.066648,7.352716],[27.18048,4.0988913],[42.580444,2.9295654],[66.52832,3.5288157],[104.539406,13.704104],[98.6219,36.472435],[59.579453,62.8917],[28.190556,57.530445],[17.951841,38.90133],[14.961957,21.920359],[16.123573,11.713805],[21.290785,5.940388],[32.029667,3.4620094],[49.246967,2.9209492],[80.67831,4.9093094],[106.06225,24.084822],[78.16658,53.804825],[40.938892,64.497345],[22.791168,50.370663],[15.4322,27.490622],[15.099595,16.078339],[18.54351,7.8293753],[25.850039,4.371794],[40.880863,2.9651554],[62.983765,3.3252711],[102.54542,11.797406],[100.76294,33.80992],[60.841614,62.458218],[27.3795,56.6251],[17.818525,38.372868],[14.94916,20.907541],[16.395008,11.093179],[22.049925,5.6012216],[33.826168,3.3169906],[52.028374,2.9652433],[87.41947,6.05132],[104.886955,26.927374],[67.49781,59.61967],[32.26883,60.80673],[19.403011,43.04106],[15.1060705,23.91719],[15.399126,14.469913]],"t":[0.0,0.11011316046003701,0.3844461364314774,0.7972099917174966,1.2399921199611446,1.7865113673670892,2.447390167283319,3.107629239704756,3.88268417516269,4.872045433743725,5.797706659554002,6.934109804294916,8.27307520778825,9.762892702799324,11.461547595544443,13.077913499231283,15.53086990568949,16.83756764808175,18.07450988340212,19.318721651036213,20.351325325168194,21.65488004736195,22.99529913555444,24.624035743617092,26.417427708483245,28.106792132507913,30.212177446719572,32.112460348213396,33.27466204048604,34.346128660035184,35.35817948583851,36.668113840783256,37.90658273564403,39.470336341408,41.09809556126542,42.897062621337795,44.65279078811043,46.92568071471189,48.04647639578809,49.12360924183431,50.28510064061886,51.34881083373543,52.59522221149232,53.92596657331732,55.525833803865986,57.280695466770524,58.974754355445995,60.974416774207455,63.065760570003235,64.16684466155851,65.19310775368139,66.20816428677806,67.62427967369084,68.75424216029114,70.3438395836795,71.90901987450208,73.76106798279135,75.45592171893118,77.77349722796164,78.97457245041599,80.11447966797712,81.36225169595501,82.40309255846108,83.71815729852207,85.06961788498312,86.70841582144669,88.5194450988655,90.20991933081874,92.36385638210932,94.21193085644724,95.45187032424677,96.58551443934655,97.63516737977987,98.93995684430786,100.0]}
```

**Pull request merged**
